export { default as BankInfo } from './bank-info'
export { default as Banner } from './banner'
export { default as ProductsAndService } from './products-service'
export { default as SucursalesSlider } from './sucursales-slider'
export { default as AboutUs } from './aboutus'
export { default as Package } from './package'